### ISSUE TITLE
Define state while restarting CouchbaseKafkaConnector 

### ISSUE THREAD

**Issue by belaazim** [couchbase/couchbase-kafka-connector#21]
Hi,
How could we push just untreated DCP events ?
For example,
I stopped my CouchbaseKafkaConnector. During this time some updates on Couchbase have been done.
I restarted my CouchbaseKafkaConnector. How to get just the updates between the stop and the restart ?
Any idea is so welcome.
Best regards,
Maherzia

**Comment by avsej** [comment]
You can specify the starting state here: https://github.com/couchbase/couchbase-kafka-connector/blob/master/src/main/java/com/couchbase/kafka/CouchbaseKafkaConnector.java#L307

**Comment by belaazim** [comment]
run( fromState, toState) 
How to set fromState from the point of last connection to couchbase ?

Example,
run kafka connection - stop connection - < Some Updates On COUCHBASE Done > - restart connection

I need to just get < Some Updates On COUCHBASE Done > between the stop and the restart.
Not to getting changes from beginning

**Comment by belaazim** [comment]
How to persist a state and then restart from it ?

**Comment by juanmav** [comment]
@avsej could you explain how to get the currentState? So we can save it and restart the service from that point if anything happens.

I also saw that the sequencenumber is saved in the zookeper. This happens when the connector send the data to kafka or when it receives the mutation?

Thanks in advance
Juan
